// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class sistema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sistema));
        
        string IMigrationMetadata.Id
        {
            get { return "201409211802004_sistema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
