// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class usuarioperfil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuarioperfil));
        
        string IMigrationMetadata.Id
        {
            get { return "201409281932555_usuarioperfil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
