// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class funcionario5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(funcionario5));
        
        string IMigrationMetadata.Id
        {
            get { return "201409060213346_funcionario5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
