// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class pergunta11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pergunta11));
        
        string IMigrationMetadata.Id
        {
            get { return "201409192247102_pergunta11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
