// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class perfiltransacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perfiltransacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201409281619061_perfiltransacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
