// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class prontuario1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prontuario1));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041516350_prontuario1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
