// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class prontuario4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prontuario4));
        
        string IMigrationMetadata.Id
        {
            get { return "201704051307267_prontuario4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
