// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class atendimento1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atendimento1));
        
        string IMigrationMetadata.Id
        {
            get { return "201703280100342_atendimento1]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
