// <auto-generated />
namespace w1Consultorio.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class empresa_chg1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(empresa_chg1));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281209425_empresa_chg1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
